### PR TITLE
Fix inconsistencies in semantic versioning and copyright

### PR DESCRIPTION
**Pull request by koluke**
Makes app more compliant with semantic versioning and improves consistency with 'Iolani School branding.

### CODE REVIEW

**Comment by maxwells-daemons** [comment]
Not sure why stuff's still showing 2.0. I'd initially named the file that
(BluePad2.0, to differentiate from existing code) but refactored everything
since.

**Comment by koluke** [comment]
@Whillikers I updated the app's version number in the [info.plist](BluePad/info.plist) file to match the version and updated the launch screen XIB file to include the 'okina in 'Iolani.

**Comment by maxwells-daemons** [comment]
Wherever possible I'd have it at 1.0 instead of 2.0.

**Comment by koluke** [comment]
K, just figured I'd address the inconsistency between the two.  The difference between the launch screen and the info.plist is misleading.

**Comment by koluke** [comment]
Okay, all version numbers are now 1.0.

**Pull request merged**
